version: '3.8'

services:
  neo4j:
    image: neo4j:5.26.0
    container_name: neo4j
    ports:
      - "7474:7474"   # Neo4j Browser UI
      - "7687:7687"   # Bolt プロトコル
    environment:
      NEO4J_AUTH: neo4j/secret_password
      NEO4J_dbms_security_procedures_unrestricted: "db.index.vector.*"
    volumes:
      - neo4j_data:/data

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: secret_password
    depends_on:
      - neo4j

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  neo4j_data:
